import { Database } from "bun:sqlite";
import * as schema from "@nexus/db/schema";
import { drizzle } from "drizzle-orm/bun-sqlite";

const sqlite = new Database(process.env.DATABASE_URL || "nexus.db");
sqlite.exec("PRAGMA journal_mode = WAL;");

export const db = drizzle(sqlite, { schema });
export type AppDatabase = typeof db;

const tableStatements = [
	`CREATE TABLE IF NOT EXISTS users (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		email text NOT NULL,
		name text NOT NULL,
		password_hash text NOT NULL,
		avatar_url text,
		google_token_encrypted text
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (email)`,
	`CREATE TABLE IF NOT EXISTS workspaces (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		owner_id text NOT NULL,
		settings_json text,
		FOREIGN KEY (owner_id) REFERENCES users(id)
	)`,
	`CREATE TABLE IF NOT EXISTS tasks (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		title text NOT NULL,
		description text,
		status text DEFAULT 'todo' NOT NULL,
		priority integer DEFAULT 4 NOT NULL,
		due_date text,
		recurrence_rule text,
		parent_task_id text,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS labels (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		color text NOT NULL,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS task_labels (
		id text PRIMARY KEY NOT NULL,
		task_id text NOT NULL,
		label_id text NOT NULL,
		FOREIGN KEY (task_id) REFERENCES tasks(id),
		FOREIGN KEY (label_id) REFERENCES labels(id)
	)`,
	`CREATE TABLE IF NOT EXISTS shopping_lists (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		store_name text NOT NULL,
		store_address text,
		store_lat real,
		store_lng real,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS shopping_items (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		quantity real DEFAULT 1 NOT NULL,
		unit text,
		estimated_price real,
		aisle text,
		is_checked integer DEFAULT 0 NOT NULL,
		list_id text NOT NULL,
		FOREIGN KEY (list_id) REFERENCES shopping_lists(id)
	)`,
	`CREATE TABLE IF NOT EXISTS shopping_routes (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		stops_json text,
		optimized_order text,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS folders (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		parent_folder_id text,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS notes (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		title text NOT NULL,
		content_blocks_json text,
		folder_id text,
		is_pinned integer DEFAULT 0 NOT NULL,
		workspace_id text NOT NULL,
		FOREIGN KEY (folder_id) REFERENCES folders(id),
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS documents (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		file_path text NOT NULL,
		mime_type text NOT NULL,
		size_bytes integer NOT NULL,
		note_id text,
		workspace_id text NOT NULL,
		FOREIGN KEY (note_id) REFERENCES notes(id),
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS calendar_connections (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		provider text DEFAULT 'google' NOT NULL,
		access_token_encrypted text NOT NULL,
		refresh_token_encrypted text NOT NULL,
		user_id text NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id)
	)`,
	`CREATE TABLE IF NOT EXISTS recipes (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		title text NOT NULL,
		description text,
		ingredients_json text,
		instructions_json text,
		prep_time integer,
		cook_time integer,
		servings integer,
		cuisine text,
		difficulty text,
		source_url text,
		image_url text,
		tags_json text,
		is_favorite integer DEFAULT 0 NOT NULL,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS sync_log (
		id text PRIMARY KEY NOT NULL,
		entity_type text NOT NULL,
		entity_id text NOT NULL,
		operation text NOT NULL,
		timestamp text NOT NULL,
		device_id text NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS databases (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		description text,
		icon text,
		cover_url text,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS database_properties (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		database_id text NOT NULL,
		name text NOT NULL,
		type text NOT NULL,
		config_json text,
		position integer DEFAULT 0 NOT NULL,
		is_visible integer DEFAULT 1 NOT NULL,
		width integer,
		FOREIGN KEY (database_id) REFERENCES databases(id)
	)`,
	`CREATE TABLE IF NOT EXISTS database_views (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		database_id text NOT NULL,
		name text NOT NULL,
		type text NOT NULL,
		config_json text,
		filters_json text,
		sorts_json text,
		group_by_property_id text,
		position integer DEFAULT 0 NOT NULL,
		FOREIGN KEY (database_id) REFERENCES databases(id)
	)`,
	`CREATE TABLE IF NOT EXISTS comments (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		content text NOT NULL,
		page_type text NOT NULL,
		page_id text NOT NULL,
		block_id text,
		parent_comment_id text,
		is_resolved integer DEFAULT 0 NOT NULL,
		author_id text NOT NULL,
		workspace_id text NOT NULL,
		FOREIGN KEY (author_id) REFERENCES users(id),
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS mentions (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		mentioned_user_id text NOT NULL,
		comment_id text,
		page_type text,
		page_id text,
		mentioned_by_user_id text NOT NULL,
		is_read integer DEFAULT 0 NOT NULL,
		FOREIGN KEY (mentioned_user_id) REFERENCES users(id),
		FOREIGN KEY (mentioned_by_user_id) REFERENCES users(id)
	)`,
	`CREATE TABLE IF NOT EXISTS share_links (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		page_type text NOT NULL,
		page_id text NOT NULL,
		token text NOT NULL,
		permission text DEFAULT 'view' NOT NULL,
		is_public integer DEFAULT 0 NOT NULL,
		expires_at text,
		created_by_id text NOT NULL,
		workspace_id text NOT NULL,
		FOREIGN KEY (created_by_id) REFERENCES users(id),
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS workspace_members (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		workspace_id text NOT NULL,
		user_id text NOT NULL,
		role text DEFAULT 'member' NOT NULL,
		invited_by_id text,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
		FOREIGN KEY (user_id) REFERENCES users(id)
	)`,
	`CREATE TABLE IF NOT EXISTS page_permissions (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		page_type text NOT NULL,
		page_id text NOT NULL,
		user_id text NOT NULL,
		permission text DEFAULT 'view' NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id)
	)`,
	`CREATE TABLE IF NOT EXISTS activity_log (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		action text NOT NULL,
		page_type text NOT NULL,
		page_id text NOT NULL,
		user_id text NOT NULL,
		details_json text,
		workspace_id text NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id),
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS page_history (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		page_type text NOT NULL,
		page_id text NOT NULL,
		version integer NOT NULL,
		snapshot_json text NOT NULL,
		edited_by_id text NOT NULL,
		FOREIGN KEY (edited_by_id) REFERENCES users(id)
	)`,
	`CREATE TABLE IF NOT EXISTS api_keys (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		name text NOT NULL,
		key_hash text NOT NULL,
		key_prefix text NOT NULL,
		scopes text DEFAULT 'read' NOT NULL,
		last_used_at text,
		expires_at text,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS webhooks (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		url text NOT NULL,
		events text NOT NULL,
		secret text NOT NULL,
		is_active integer DEFAULT 1 NOT NULL,
		last_triggered_at text,
		failure_count integer DEFAULT 0 NOT NULL,
		workspace_id text NOT NULL,
		FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
	)`,
	`CREATE TABLE IF NOT EXISTS webhook_deliveries (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		webhook_id text NOT NULL,
		event text NOT NULL,
		payload_json text NOT NULL,
		response_status integer,
		response_body text,
		success integer DEFAULT 0 NOT NULL,
		FOREIGN KEY (webhook_id) REFERENCES webhooks(id)
	)`,
	`CREATE TABLE IF NOT EXISTS database_rows (
		id text PRIMARY KEY NOT NULL,
		created_at text NOT NULL,
		updated_at text NOT NULL,
		deleted_at text,
		sync_version integer DEFAULT 0 NOT NULL,
		database_id text NOT NULL,
		values_json text DEFAULT '{}' NOT NULL,
		position integer DEFAULT 0 NOT NULL,
		FOREIGN KEY (database_id) REFERENCES databases(id)
	)`,
];

export function initializeDatabase() {
	for (const stmt of tableStatements) {
		sqlite.exec(stmt);
	}
	// FTS5 virtual table for full-text search on notes
	sqlite.exec(`
		CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5(
			title,
			content,
			content_rowid='rowid',
			tokenize='porter unicode61'
		)
	`);
	sqlite.exec("PRAGMA foreign_keys = ON;");
}
